### ISSUE TITLE
Include "Docs" in export [Feature Request]

### ISSUE THREAD

**Issue by DarkSuniuM** [Vyoam/insomnia-plugin-postman-export#1]
Hello,

Thanks for this amazing plugin,

It would be awesome if it could also export the Docs from Insomnia.

**Comment by Vyoam** [comment]
Thanks a lot @DarkSuniuM for the feedback. Will try to do this along with some other todo in a couple of weeks (FYI, just updated readme to capture all the todo related links).

Else, if you or any other user here is interested to contribute, (and for my own reference) I think these steps are needed...
* verify if Postman export-import does honor the doc/description details (not sure right now)
* Identify the corresponding properties where the doc data is stored in Insomnia and Postman export files, and update postman-export.js to incorporate it.. probably, within transformItem() method in postman-export.js.

Personally I'd be also interested to see if [apimatic](https://www.apimatic.io/transformer/#supported-formats) supports the doc info export or not.

**Comment by Vyoam** [comment]
The below commit added the required support...
https://github.com/Vyoam/insomnia-plugin-postman-export/commit/9e3e013e475ac948e64a2e73fff17a5f4a2a45c1

The latest version has it.

Forgot to update here earlier.
