### ISSUE TITLE
Insomnia not allowing to download the plugin

### ISSUE THREAD

**Issue by MavGitt** [Vyoam/insomnia-plugin-postman-export#12]
I am trying to install this plugin via [https://insomnia.rest/plugins/insomnia-plugin-postman-export] but Insomnia is complaining that the plugin has certain issues.
<img width="757" alt="image" src="https://github.com/Vyoam/insomnia-plugin-postman-export/assets/65035132/e2d38598-0012-49a6-bf6c-0943fb2d0b02">

**Comment by Vyoam** [comment]
Couldn't reproduce (screenshot below). Though, I see a related issue in Insomnia repo: https://github.com/Kong/insomnia/issues/6576

As a workaround, you could download/clone the repo to the [plugin location](https://github.com/Vyoam/insomnia-plugin-postman-export#for-reference-insomnia-plugin-locations) applicable to your OS, and run _npm install_ (I'm sure you can figure out npm, if you aren't already aware).

![image](https://github.com/Vyoam/insomnia-plugin-postman-export/assets/1176140/cd25fcb7-5921-4d01-a565-999bb3e970ab)

**Comment by GonzaloCalandria** [comment]
Hello @Vyoam I'm having the same issue as @MavGitt .
This is happening on windows and the screenshot that you've sent (@Vyoam ) is before the error occurs. The error happens when you click the Install Plugin button.
![image](https://github.com/Vyoam/insomnia-plugin-postman-export/assets/2286280/22d4f759-e345-4149-9a01-6633acdb84de)

**Comment by GonzaloCalandria** [comment]
Ok, I just found the problem. I'll let here the solution.

In the textbox where it says "npm-package-name" you need to write the name of the folder that appears when you click "Reveal Folder" button. In my case was "insomnia-plugin-postman-export". 
Once you put that name and click Install Plugin. The plugin is installed without any issues.

CC: @Vyoam @MavGitt

**Comment by MavGitt** [comment]
That's helpful @GonzaloCalandria
