### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by jannie-louwrens** [Vyoam/insomnia-plugin-postman-export#4]
I am trying to install the plugin using the install button on https://insomnia.rest/plugins/insomnia-plugin-postman-export
The installation is failing with the stack trace:
`Yarn error {"type":"warning","data":"package.json: No license field"}`

**Comment by Vyoam** [comment]
This might be related to insomnia core. See the latest comment: https://github.com/Kong/insomnia/issues/2656#issuecomment-999085568
So, I'll recheck on any updates there in a week or so, and see if a fix at plugin level is needed.

As a workaround, you may extract this pre-built artifact and put it in the Insomnia plugins folder (paths mentioned in readme).
[insomnia-plugin-postman-export-0.8.4.zip](https://github.com/Vyoam/insomnia-plugin-postman-export/files/7833641/insomnia-plugin-postman-export-0.8.4.zip)
Of course, users who have npm installed can build it themselves.

**Comment by jannie-louwrens** [comment]
Thanks for the work around, it worked.
