### ISSUE TITLE
Export not working. Prompt for export path never appears

### ISSUE THREAD

**Issue by ehausen** [Vyoam/insomnia-plugin-postman-export#9]
I'm not able to export anything. 

I get first two prompts: Regex filter and CSV question. After clicking on OK on the CSV prompt (leaving it empty) the modal just closes and nothing happens.

No messages in the dev tools console.

From the plugin code I see that it is supposed to ask for output folder.

**Comment by Vyoam** [comment]
Will try to check this weekend.
Do note that if a lot of requests are selected, it does take time. Will recheck the logging for that.

**Comment by JeepLavoie** [comment]
I had the same problem with using this plugin today. I put a *Request Id CSV* and the path for saving prompt. But without a Request Id the prompt didn't show.

**Comment by Vyoam** [comment]
I have released 0.8.8 to fix this.

The CSV prompt has a blank as the default input. It seems there has been an internal change in the prompt component, which causes it to fail for blank inputs. As a workaround, I have put 'none' as the default (really, one can use any random string which is not a request id).
And of course in 0.8.7 too, one could manually type a random string to make it work.
